# Generated by Django 4.0.1 on 2022-01-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='url',
            new_name='link',
        ),
    ]
